# Generated by Django 4.2.7 on 2023-11-24 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0004_alter_bonds_ytm_alter_bonds_denomination'),
        ('transaction', '0003_transaction_sell_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='bonds',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='count',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='sell_status',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transfer_type',
            field=models.CharField(choices=[('SELL', 'SELL'), ('BUY', 'BUY'), ('ENROLLMENT', 'ENROLLMENT'), ('DEDUCTION', 'DEDUCTION'), ('PAYOUT', 'PAYOUT')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Bargain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Кількість')),
                ('bonds', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonds.bonds')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transaction.transaction')),
            ],
            options={
                'verbose_name': 'Угода',
                'verbose_name_plural': 'Угоди',
            },
        ),
    ]
