# Generated by Django 4.2.7 on 2023-11-18 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('photo', models.ImageField(upload_to='photos/currencyType/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Тип валюти',
                'verbose_name_plural': 'Типи валют',
            },
        ),
        migrations.CreateModel(
            name='Bonds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('YTM', models.BooleanField(default=False, verbose_name='Дохід до погашення')),
                ('name', models.CharField(max_length=255, verbose_name='Номер')),
                ('quantity', models.IntegerField(verbose_name='Кількість')),
                ('repayment_date', models.DateTimeField(verbose_name='Дата розміщення')),
                ('denomination', models.DecimalField(decimal_places=0, max_digits=9, verbose_name='Номінал')),
                ('placement_period', models.DurationField(verbose_name='Термін розміщення')),
                ('coupon_rate', models.FloatField(verbose_name='Ставка купона')),
                ('number_payment', models.IntegerField(blank=True, verbose_name='Кількість виплати купона')),
                ('coupon', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Купон')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Ціна')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('currency_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonds.currencytype', verbose_name='Тип валюти')),
            ],
            options={
                'verbose_name': 'Облігації',
                'verbose_name_plural': 'Облігації',
            },
        ),
    ]
