# Generated by Django 4.2.7 on 2023-11-18 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonds',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='bonds',
            name='price',
        ),
    ]
