# Generated by Django 4.2.7 on 2023-11-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0002_remove_bonds_coupon_remove_bonds_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonds',
            name='placement_period',
            field=models.DateTimeField(verbose_name='Дата погашення'),
        ),
    ]
