# Generated by Django 4.2.7 on 2023-11-21 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0003_alter_bonds_placement_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonds',
            name='YTM',
            field=models.BooleanField(blank=True, default=False, verbose_name='Дохід до погашення'),
        ),
        migrations.AlterField(
            model_name='bonds',
            name='denomination',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Номінал'),
        ),
    ]
