# Generated by Django 4.2.7 on 2023-11-25 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0005_alter_bonds_number_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonds',
            name='number_payment',
            field=models.IntegerField(blank=True, default=1, verbose_name='Кількість виплати купона'),
        ),
    ]
