# Generated by Django 4.2.7 on 2023-11-21 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funds', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Вільні кошти')),
                ('residue', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Залишок')),
                ('blocked', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Заблоковані')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('users', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Портфель',
                'verbose_name_plural': 'Портфелі',
            },
        ),
    ]
