# Generated by Django 4.2.7 on 2023-11-21 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='number',
            field=models.CharField(default=1, max_length=50, verbose_name='Номер рахунку'),
            preserve_default=False,
        ),
    ]
