# Generated by Django 4.2.7 on 2023-11-21 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_bill_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='slug',
        ),
    ]
