# Generated by Django 4.2.7 on 2023-11-22 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_rename_users_bill_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='residue',
        ),
        migrations.AlterField(
            model_name='bill',
            name='funds',
            field=models.DecimalField(decimal_places=2, default=999999999, max_digits=9, verbose_name='Вільні кошти'),
        ),
    ]
