# Generated by Django 4.2.7 on 2023-11-22 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_remove_bill_residue_alter_bill_funds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='funds',
            field=models.DecimalField(decimal_places=2, default=999999999, max_digits=15, verbose_name='Вільні кошти'),
        ),
    ]
