# Generated by Django 4.2.7 on 2023-11-24 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0004_alter_bonds_ytm_alter_bonds_denomination'),
        ('portfolio', '0006_alter_bill_funds'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillBonds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Кількість')),
                ('Bonds', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonds.bonds')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.bill')),
            ],
            options={
                'verbose_name': 'Портфель облігацій',
                'verbose_name_plural': 'Портфелі облігацій',
            },
        ),
    ]
